name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://kreuzwerker-blog.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
  VERSION: ${{ github.sha }}
  GIT_REF: ${{ github.ref }}
  PACTICIPANT: "pact-consumer"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup jdk-17
      uses: actions/setup-java@main
      with:
        java-version: 17
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean verify -B
    - name: Publish pacts
      uses: roycdiscovery/pact-publish-pactfiles-action@v1.0
      env:
        pactfiles: target/pacts
        application_name: ${{ env.PACTICIPANT }}
        version: ${{ env.VERSION }}
        pact_broker: ${{ env.PACT_BROKER_BASE_URL }}
        pact_broker_token: ${{ env.PACT_BROKER_TOKEN }}

  can-i-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: pactflow/actions/can-i-deploy@v0.0.2
        env:
          to: "production"
          pact_broker: ${{ env.PACT_BROKER_BASE_URL }}
          pact_broker_token: ${{ env.PACT_BROKER_TOKEN }}
          application_name: ${{ env.PACTICIPANT }}
          version: ${{ env.VERSION }}
